backend:
  name: github
  repo: julianmarmier/julianm-portfolio-netlify
  branch: final-redesign

# name: git-gateway
# branch: master

media_folder: static/img
public_folder: /img
logo_url: /julianm_logo.svg
site_url: https://julianm.tk/
display_url: https://julianm.tk/

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Body Images"
        label_singular: "image"
        name: "images"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Alt text", name: "alt", widget: "string"}
      - { label: "Thumbnail", name: "thumbnail", widget: "image"}
  - name: "staticContent"
    label: "Static Content"
    files:
      - label: "About"
        name: "about"
        file: "content/static.yml"
        fields:
        - { label: "In a Nutshell", name: "intro", widget: "markdown"}
        - { label: "Present", name: "present", widget: "markdown"}
        - label: "Past"
          name: "past"
          label_singular: "Past Experience"
          widget: "list"
          field: { label: "Experience", name: "experience", widget: "markdown" }